# Generated by Django 5.1.1 on 2024-11-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='sale',
            new_name='sale_id',
        ),
    ]
